spring.application.name=playwright
playwright.cucumber.compilationMode=H
playwright.cucumber.browser=chrome
playwright.cucumber.envUrl=https://www.makemytrip.com/
playwright.cucumber.testData=testfile/TestData.xlsx
playwright.cucumber.videopath=target/videos/
playwright.cucumber.srcShotPath=target/screenshots/
playwright.cucumber.apiUrl=https://api.restful-api.dev/objects/7
#spring.datasource.username=
#spring.datasource.password=
#spring.datasource.url=
#spring.datasource.driver-class-name=
